services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: productos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    entrypoint: ["wait-for-it", "postgres:5432", "--timeout=30", "--strict", "--", "java", "-jar", "app.jar"]